In [6]:
# Show that python is row majored
import numpy as np

A = np.arange(1, 26).reshape(5, 5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
# Row iteration in python
for row in A:
    row += 1
print A

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]


In [12]:
try:
    A[8]
except IndexError:
    print "No linear indexing"

No linear indexing
